/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViagensRouteImport } from './routes/viagens'
import { Route as RecebimentosRouteImport } from './routes/recebimentos'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CadastrosRouteImport } from './routes/cadastros'
import { Route as IndexRouteImport } from './routes/index'

const ViagensRoute = ViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentosRoute = RecebimentosRouteImport.update({
  id: '/recebimentos',
  path: '/recebimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosRoute = CadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas': typeof DespesasRoute
  '/recebimentos': typeof RecebimentosRoute
  '/viagens': typeof ViagensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas': typeof DespesasRoute
  '/recebimentos': typeof RecebimentosRoute
  '/viagens': typeof ViagensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas': typeof DespesasRoute
  '/recebimentos': typeof RecebimentosRoute
  '/viagens': typeof ViagensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastros'
    | '/configuracoes'
    | '/despesas'
    | '/recebimentos'
    | '/viagens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastros'
    | '/configuracoes'
    | '/despesas'
    | '/recebimentos'
    | '/viagens'
  id:
    | '__root__'
    | '/'
    | '/cadastros'
    | '/configuracoes'
    | '/despesas'
    | '/recebimentos'
    | '/viagens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrosRoute: typeof CadastrosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DespesasRoute: typeof DespesasRoute
  RecebimentosRoute: typeof RecebimentosRoute
  ViagensRoute: typeof ViagensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viagens': {
      id: '/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof ViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimentos': {
      id: '/recebimentos'
      path: '/recebimentos'
      fullPath: '/recebimentos'
      preLoaderRoute: typeof RecebimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros': {
      id: '/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof CadastrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrosRoute: CadastrosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DespesasRoute: DespesasRoute,
  RecebimentosRoute: RecebimentosRoute,
  ViagensRoute: ViagensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
